os:
  - linux
language: node_js

node_js:
  - "4"
  - "5"
  - "6"

install:
  - npm install coveralls

before_script:
  - npm install

script:
  - npm test

after_success:
  - cat coverage/lcov.info | node_modules/.bin/coveralls
